### PR TITLE
Update examples with umount

### PR DESCRIPTION
**Pull request by DJDevon3**
Help avoid data corruption by unmounting SD card after use

### CODE REVIEW

**Comment by tekktrik** [comment]
This looks good to me, did you test these as well?

**Comment by DJDevon3** [comment]
@tekktrik Only tested the TFT featherwing example and can confirm it works well. The other 2 I did just because I was in there. Should I not submit things I cannot explicitly test?  It seemed like a shame to leave the other 2 examples alone without umount.  I probably should have specified that in the original commit sorry.

**Comment by tekktrik** [comment]
No, totally fine to PR things you haven't tested!  Just wanted to check, definitely always makes me more confident when it is tested is all :)

**Comment by tekktrik** [comment]
I'm out today but will look tomorrow!

**Review by tekktrik — COMMENTED** [review]
Does it make sense to just take out `TAKE_SCREENSHOT` (assuming it's value would always be true) and always begin the block of taking the screenshot and then unmounting the SD card?  Or is there a specific reason it would be helpful to toggle it, and why that default value is `False`?

**Comment by DJDevon3** [comment]
Take screenshot is False by default. Set to true to take a screenshot. 

A good real world example is at the very end of my [feather weather project](https://github.com/DJDevon3/My_Circuit_Python_Projects/blob/main/Boards/espressif/Adafruit%20Feather%20ESP32-S3/3.5%20TFT%20Featherwing/Online%20OpenWeatherMaps%20Weatherstation/code.py). I always want it available to use but I don't use it regularly.  When I've updated something worthy of updating the screenshot for learn guides or gists it's a one click process.  I included it because I believe its in everyone's best interest to become accustomed to using it in that way.

Technically it doesn't need to be there... but then neither does umount. It adds safety measures so you don't
1. take a screenshot when you don't mean to (depending on screen size and MCU power this can take up to 5 minutes and you cannot back out once started)
2. possibly corrupt data because you're unaware how important umount is.

They're definitely features I wish I would have known about and started using from the beginning of my time in the circuit python world.

**Comment by DJDevon3** [comment]
@FoamyGuy that's a great point and points out a flaw in the way I've been using it.  Will take another shot at improving it. Thank you for the excellent guidance.

**Comment by DJDevon3** [comment]
Moved SD Card initialization into take screenshot if statement. Works well. 
Tested the bitmapsaver_screenshot_simpletest.py & bitmapsaver_screenshot_tft_featherwing.py. example successfully

screenshot

was unable to successfully test the bitmapsaver_simpletest.py example on my tft featherwing because sck in use.

**Review by FoamyGuy — APPROVED** [review]
The current version looks good to me. I tested the simpletest successfully on a PyPortal Titano.

**Pull request merged**
